-- Fetch the first 100 rows from the SIMULATION_DATA table
SELECT * FROM HEALTHDB.HEALTHSCHEMA.SIMULATION_DATA LIMIT 100;

-- Find the minimum and maximum admission dates from the SIMULATION_DATA table
SELECT MIN(ADMISSION_DATE), MAX(ADMISSION_DATE) FROM HEALTHDB.HEALTHSCHEMA.SIMULATION_DATA LIMIT 100;

-- Find the minimum admission date and the current date minus 37 days from the SIMULATION_DATA table
SELECT MIN(ADMISSION_DATE), CURRENT_DATE - 37 FROM HEALTHDB.HEALTHSCHEMA.SIMULATION_DATA;

---- Scoring Script

-- Create a base table with cleaned and coalesced columns from the SIMULATION_DATA table
WITH BASE AS (
    SELECT 
        CASE_ID,
        COALESCE(HOSPITAL_CODE,0) AS HOSPITAL_CODE,
        COALESCE(HOSPITAL_TYPE_CODE,'None') AS HOSPITAL_TYPE_CODE,
        COALESCE(CITY_CODE_HOSPITAL,0) AS CITY_CODE_HOSPITAL,
        COALESCE(HOSPITAL_REGION_CODE,'None') AS HOSPITAL_REGION_CODE,
        COALESCE(AVAILABLE_EXTRA_ROOMS_IN_HOSPITAL,0) AS AVAILABLE_EXTRA_ROOMS_IN_HOSPITAL,
        COALESCE(DEPARTMENT,'None') AS DEPARTMENT,
        COALESCE(WARD_TYPE,'None') AS WARD_TYPE,
        COALESCE(WARD_FACILITY_CODE,'None') AS WARD_FACILITY_CODE,
        COALESCE(BED_GRADE,0) AS BED_GRADE,
        PATIENTID,
        COALESCE(CITY_CODE_PATIENT,0) AS CITY_CODE_PATIENT,
        COALESCE(TYPE_OF_ADMISSION,'None') AS TYPE_OF_ADMISSION,
        COALESCE(SEVERITY_OF_ILLNESS,'Minor') AS SEVERITY_OF_ILLNESS,
        COALESCE(VISITORS_WITH_PATIENT,0) AS VISITORS_WITH_PATIENT,
        COALESCE(AGE,'None') AS AGE,
        COALESCE(ADMISSION_DEPOSIT,0) AS ADMISSION_DEPOSIT,
        ADMISSION_DATE,
        DISCHARGE_DATE
    FROM HEALTHDB.HEALTHSCHEMA.SIMULATION_DATA
),
    
-- Create a table with additional features derived from the base table
BASE_WITH_FEATURES AS (
    SELECT *,
        MONTHNAME(ADMISSION_DATE) AS ADMISSION_MONTH,
        DAYNAME(ADMISSION_DATE) AS ADMISSION_DAY,
        CONCAT(TYPE_OF_ADMISSION,'-',SEVERITY_OF_ILLNESS) AS ADMISSION_ILLNESS,
        CONCAT(SEVERITY_OF_ILLNESS,'-',BED_GRADE) AS ILLNESS_BEDGRADE,
        CONCAT(DEPARTMENT,'-',SEVERITY_OF_ILLNESS) AS DEPARTMENT_ILLNESS,
        DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE) AS LOS
    FROM BASE 
)    

-- Select all columns from the final table with features where the admission date is 37 days ago from the current date
SELECT * FROM BASE_WITH_FEATURES WHERE ADMISSION_DATE = CURRENT_DATE - 37;

---- LOGGING TABLE

-- Fetch all rows from the TEMP_LOS_PREDICTION_MODEL_LOGGING_TABLE_HARI table
SELECT * FROM HEALTHDB.HEALTHSCHEMA.TEMP_LOS_PREDICTION_MODEL_LOGGING_TABLE_HARI;
